In [1]:
import pandas as pd
import os

In [6]:
HES = pd.read_csv('../data/HES/July/2018-07-01.csv', header=None, sep=";")

In [11]:

# dictonary for sensor names

appliance_dict = {
    2: "Dishwasher",
    3: "Treadmill",
    4: "Car charger",
    5: "Microwave",
    6: "Fridge",
    7: "Air exchanger",
    8: "Heat bedroom #1",
    9: "Heat bedroom #2",
    10: "Heat kitchen",
    11: "Heat living room",
    12: "Heat bedroom #3",
    13: "Heat dining room",
    14: "Water heater",
    15: "Office outlet #3",
    16: "Heat basement",
    17: "Office outlet #2",
    18: "Basement bathroom",
    19: "Office outlet #1",
    20: "Heat garage",
    21: "Garage/Basement outlets",
    22: "Oven",
    23: "Outdoor outlets",
    24: "Whirlpool bath",
    25: "Powder room outlets",
    26: "Lights Powder room/kitchen",
    27: "Lights bedroom #1 and #3",
    28: "Basement outlets",
    29: "Living/dining room outlets",
    30: "Bedroom #2 outlets",
    31: "Secondary outlets",
    32: "Washing machine",
    33: "Air Conditioning",
    34: "Basement/powder room outlets",
    35: "Kitchen outlet #1",
    36: "Kitchen outlet #2",
    37: "Kitchen outlet #3",
    38: "Kitchen outlet #4",
    39: "Dryer",
    40: "Towel dryer"
}

In [10]:
# process data for one day and return it as a dataframe
def process_file(file_name):
    # get date from file name
    date = os.path.basename(file_name).split(".")[0]
    
    with open(file_name, "r") as f:
        # read file 
        HES = pd.read_csv(f, header=None, sep=";")

        # name columns
        HES.columns = ["time", "sensor", "consumption"]
        
        # add date to time column
        HES["time"] = date + " " + HES["time"]

        # time column to datetime
        HES["time"] = pd.to_datetime(HES["time"], format="%Y-%m-%d %H:%M:%S")
        HES = process_table(HES)

    return HES


# pivots the table so that each appliance has its own column with consumption values and adds a column for total consumption
def process_table(df):
    # replace sensor number with appliance name
    df["sensor"] = df["sensor"].replace(appliance_dict)

    # pivot the table so that each appliance has its own column with consumption values
    df = df.pivot(index='time', columns='sensor', values='consumption')

    # add column for total consumption
    df["Total Consumption"] = df.sum(axis=1)  

    df = df.rename_axis(None, axis=1)
    return df

    
process_file("../data/HES/July/2018-07-01.csv").head()

        time  sensor  consumption
0 2018-07-01       2         0.20
1 2018-07-01       3         0.27
2 2018-07-01       4         0.17
3 2018-07-01       5         0.29
4 2018-07-01       6         0.23

,Air Conditioning,Air exchanger,Basement bathroom,Basement outlets,Basement/powder room outlets,Bedroom #2 outlets,Car charger,Dishwasher,Dryer,Fridge,...,Outdoor outlets,Oven,Powder room outlets,Secondary outlets,Towel dryer,Treadmill,Washing machine,Water heater,Whirlpool bath,Total Consumption
time,,,,,,,,,,,,,,,,,,,,,
2018-07-01 00:00:00,0.31,0.21,0.23,0.20,0.58,0.21,0.17,0.20,0.22,0.23,...,0.64,0.18,0.21,0.17,0.20,0.27,0.23,0.23,0.23,13.97
2018-07-01 00:00:01,0.29,0.20,0.23,0.18,0.57,0.20,0.17,0.18,0.23,0.23,...,0.63,0.17,0.21,0.17,0.20,0.25,0.23,0.23,0.23,13.90
2018-07-01 00:00:02,0.30,0.17,0.20,0.17,0.58,0.21,0.19,0.20,0.23,0.23,...,0.60,0.18,0.22,0.17,0.22,0.27,0.23,0.24,0.23,13.78
2018-07-01 00:00:03,0.29,0.20,0.20,0.17,0.60,0.20,0.17,0.20,0.23,0.23,...,0.64,0.20,0.19,0.17,0.20,0.27,0.23,0.23,0.23,13.86
2018-07-01 00:00:04,0.29,0.21,0.17,0.17,0.60,0.22,0.17,0.20,0.23,0.23,...,0.62,0.19,0.19,0.18,0.18,0.26,0.24,0.23,0.22,13.75