In [3]:
%pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-12.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.9 MB)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.10/site-packages (from pyarrow) (1.23.5)
Installing collected packages: pyarrow
Successfully installed pyarrow-12.0.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [25]:
metadata_hue = pd.read_parquet("./Energy_graph/data/energy-forecast/data/processed/HUE_metadata.parquet")

metadata_refit = pd.read_parquet("./Energy_graph/data/energy-forecast/data/processed/refit_metadata.parquet")

In [42]:
H = pd.read_parquet("./Energy_graph/data/energy-forecast/data/processed/HUE_residentials.parquet")
H

                       timestamp  residential_id  energy
0      2012-06-01 01:00:00-07:00               1  1011.0
1      2012-06-01 02:00:00-07:00               1   451.0
2      2012-06-01 03:00:00-07:00               1   505.0
3      2012-06-01 04:00:00-07:00               1   441.0
4      2012-06-01 05:00:00-07:00               1   468.0
...                          ...             ...     ...
616041 2018-03-25 19:00:00-07:00              19  2050.0
616042 2018-03-25 20:00:00-07:00              19  1990.0
616043 2018-03-25 21:00:00-07:00              19  2120.0
616044 2018-03-25 22:00:00-07:00              19  2200.0
616045 2018-03-25 23:00:00-07:00              19  1890.0

[592621 rows x 3 columns]

In [28]:
metadata_hue.drop(columns=["region", "country"], inplace=True)

In [32]:
metadata_hue

,residential_id,first_reading,last_reading,house_type,facing,RUs,EVs,SN,FAGF,HP,...,NAC,FAC,PAC,BHE,IFRHE,WRHIR,GEOTH,lat,lon,tz
residential_id,,,,,,,,,,,,,,,,,,,,,
1,1,2012-06-01,2015-10-03,bungalow,S,1.0,0.0,1.0,1,1,...,0,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
2,2,2016-06-09,2019-11-20,duplex,N,0.0,0.0,2.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
3,3,2015-01-27,2018-01-29,modern,S,2.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
4,4,2015-01-30,2018-01-29,character,W,1.0,0.0,0.0,1,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
5,5,2015-01-30,2018-01-29,modern,S,1.0,0.0,0.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
6,6,2015-01-30,2018-01-29,apartment,SW,0.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
8,8,2015-02-21,2018-02-20,character,S,0.0,0.0,0.0,1,0,...,0,0,1,0,0,0,0,49.083333,-122.350,Canada/Pacific
9,9,2015-05-01,2018-02-21,special,S,0.0,0.0,0.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
10,10,2015-02-21,2018-02-20,special,S,0.0,0.0,0.0,1,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
11,11,2015-02-21,2018-02-20,duplex,N,0.0,0.0,0.0,1,0,...,1,0,0,1,1,0,0,49.083333,-122.350,Canada/Pacific
12,12,2015-02-21,2018-02-20,apartment,NW,0.0,0.0,0.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
13,13,2015-02-21,2018-02-20,special,N,1.0,0.0,0.0,1,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
14,14,2015-02-21,2018-02-20,modern,S,1.0,0.0,0.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
15,15,2015-09-29,2018-02-20,bungalow,ENE,1.0,0.0,0.0,1,0,...,1,0,0,0,0,0,0,48.511000,-123.413,Canada/Pacific
16,16,2017-11-01,2019-02-18,apartment,NE,0.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
17,17,2016-06-01,2017-04-29,apartment,SW,0.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
18,18,2015-03-16,2018-03-15,bungalow,E,0.0,85.0,0.0,1,0,...,0,0,1,0,0,0,0,49.083333,-122.350,Canada/Pacific
19,19,2015-03-26,2018-03-25,special,W,0.0,0.0,0.0,1,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
20,20,2015-08-21,2018-04-20,character,N,0.0,0.0,0.0,0,0,...,1,0,0,0,0,1,0,49.083333,-122.350,Canada/Pacific
21,21,2017-11-01,2018-06-04,laneway,W,0.0,0.0,0.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
22,22,2016-06-29,2018-06-05,apartment,S,0.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
23,23,2017-07-27,2020-04-05,apartment,SE,0.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
24,24,2017-05-13,2020-05-12,modern,S,0.0,0.0,0.0,1,0,...,0,1,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
25,25,2017-05-15,2020-05-14,character,S,0.0,0.0,0.0,0,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific
26,26,2019-11-29,2020-05-20,apartment,NNW,0.0,0.0,0.0,0,0,...,1,0,0,0,0,0,1,49.083333,-122.350,Canada/Pacific
27,27,2019-03-06,2020-05-20,apartment,NW,0.0,0.0,0.0,0,0,...,1,0,0,1,0,0,0,49.083333,-122.350,Canada/Pacific
28,28,2018-08-01,2020-05-19,special,N,0.0,0.0,0.0,1,0,...,1,0,0,0,0,0,0,49.083333,-122.350,Canada/Pacific

In [30]:
metadata_refit.drop(columns=["country", "location"], inplace=True)
metadata_refit['name'] = 'house_' + metadata_refit['house'].astype(str) + '_refit'

In [31]:
metadata_refit

,house,occupancy,construction_year,appliances_owned,house_type,house_size,lat,lon,tz,appliances,name
house,,,,,,,,,,,
1,1,2,1975-1980,35,Detached,4 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge, chest freezer, upright free...",house_1_refit
2,2,4,-,15,Semi-detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer, washing machine, di...",house_2_refit
3,3,2,1988,27,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, toaster, fridge-freezer, freezer, t...",house_3_refit
4,4,2,1850-1899,33,Detached,4 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge, freezer, fridge-freezer, wa...",house_4_refit
5,5,4,1878,44,Mid-terrace,4 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer, tumble dryer 3, dis...",house_5_refit
6,6,2,2005,49,Detached,4 bed,52.7709,-1.2097,Europe/London,"aggregate, freezer (utility room), washing mac...",house_6_refit
7,7,4,1965-1974,25,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge, freezer (garage), freezer, ...",house_7_refit
8,8,2,1966,35,Detached,2 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge, freezer, dryer, washing mac...",house_8_refit
9,9,2,1919-1944,24,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer, washer dryer, washi...",house_9_refit
10,10,4,1919-1944,31,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, magimix (blender), freezer, chest f...",house_10_refit
11,11,1,1945-1964,25,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge, fridge-freezer, washing mac...",house_11_refit
12,12,3,1991-1995,26,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer, television site(lou...",house_12_refit
13,13,4,post 2002,28,Detached,4 bed,52.7709,-1.2097,Europe/London,"aggregate, television site, unknown, washing m...",house_13_refit
15,15,1,1965-1974,19,Semi-detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer, tumble dryer, washi...",house_15_refit
16,16,6,1981-1990,48,Detached,5 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer (1), fridge-freezer ...",house_16_refit
17,17,3,mid 60s,22,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, freezer (garage), fridge-freezer, t...",house_17_refit
18,18,2,1965-1974,34,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge(garage), freezer(garage), fr...",house_18_refit
19,19,4,1945-1964,26,Semi-detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge & freezer, washing machine, ...",house_19_refit
20,20,2,1965-1974,39,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge, freezer, tumble dryer, wash...",house_20_refit
21,21,4,1981-1990,23,Detached,3 bed,52.7709,-1.2097,Europe/London,"aggregate, fridge-freezer, tumble dryer, washi...",house_21_refit

In [38]:
metadata_uciml = pd.read_parquet("./Energy_graph/data/energy-forecast/data/processed/uciml_household.parquet")
letra.columns

Index(['global_active_power', 'global_reactive_power', 'voltage',
       'global_intensity', 'sub_metering_1', 'sub_metering_2',
       'sub_metering_3', 'timestamp', 'unmetered', 'country', 'region', 'lat',
       'lon', 'tz'],
      dtype='object')

In [40]:
letra.drop(columns=['global_active_power', 'global_reactive_power', 'voltage',
       'global_intensity', 'sub_metering_1', 'sub_metering_2',
       'sub_metering_3', 'timestamp', 'unmetered', 'country', 'region'], inplace=True)

letra